version : '3'

services:
        zookeeper:
                image: wurstmeister/zookeeper
                volumes:
                        - zookeeper_storage_new:/var/lib/zookeeper
                container_name: zookeeper
                ports:
                        - "2181:2181"   #externalport:internalport
                networks:
                        - zoonet

        kafka:
                image: wurstmeister/kafka
                volumes:
                        - kafka_storage_new:/var/lib/kafka
                container_name: kafka
                ports:
                        - "5659:9092"
                environment:
                        KAFKA_ADVERTISED_HOST_NAME: localhost
                        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 #2181 external port
                networks:
                        - kafnet                       


volumes:
        zookeeper_storage_new:
        kafka_storage_new:        
networks:
        zoonet:
        kafnet: